wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
    exitMessage:
      display: false
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [3, 36, 36, 3]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [2, 21, 2]
  refreshInterval: 100ms
  openFileUtil: "open"
  mods:
    peers:
      title: "peers"      
      args: []
      cmd: "dtn7-peers"
      type: "cmdrunner"
      pty: false
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true 
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 2s
    bundles:
      title: "bundles"      
      args: []
      cmd: "dtn7-bundles"
      type: "cmdrunner"
      pty: false
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true      
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 2s    
    
