name: test

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: 'checkout reference (sha/branch)'
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-12, ubuntu-22.04, windows-2022]
        java-version: [17, 22]

    env:
      JAVA_OPTS: -Xmx4g

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version}}
        distribution: 'zulu'

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: install jsdom
      run: npm install jsdom


    - name: compile
      run: sbt --client compile

    - name: compile tests
      run: sbt --client Test/compile

    - name: test
      continue-on-error: true
      run: sbt --client test

    - name: test again (quick)
      run: sbt --client testQuick

